# docker-compose.yml
# ----------------------------------------------------------------------------
# Composes Docker containers and volumes to a runnable application
# ----------------------------------------------------------------------------
#
---
services:

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeit
      POSTGRES_PORT: "5432"
      POSTGRES_DB: cloudtrain
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--username", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  downstream:
    image: docker.cloudtrain.aws.msgoat.eu/cloudtrain/cnj-persistence-sql-downstream:latest
    environment:
      DOCKER_JAVA_OPTS: "-Xms1g -Xmx1g"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://oidc.cloudtrain.aws.msgoat.eu/realms/cloudtrain/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://oidc.cloudtrain.aws.msgoat.eu/realms/cloudtrain

  backend:
    image: docker.cloudtrain.aws.msgoat.eu/cloudtrain/cnj-persistence-sql-backend-spring:latest
    ports:
      - "38080:8080"
    environment:
      DOCKER_JAVA_OPTS: "-Xms1g -Xmx1g"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://oidc.cloudtrain.aws.msgoat.eu/realms/cloudtrain/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://oidc.cloudtrain.aws.msgoat.eu/realms/cloudtrain
      CLOUDTRAIN_SERVICES_DOWNSTREAM_URL: http://downstream:8080
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_NAME: cloudtrain
      POSTGRES_DB_USER: postgres
      POSTGRES_DB_PASSWORD: changeit
    depends_on:
      downstream:
        condition: service_started
      postgres:
        condition: service_healthy
